<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="book.xsl"?>

<!DOCTYPE bookstore [
<!ELEMENT bookstore (book+)>
<!ELEMENT book (title, author, publisher, year, price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>

<bookstore>
    <book>
        <title>The Cat in the Hat</title>
        <author>Dr. Seuss</author>
        <publisher>Random House</publisher>
        <year>1957</year>
        <price>$10.99</price>
    </book>
    <book>
        <title>Green Eggs and Ham</title>
        <author>Dr. Seuss</author>
        <publisher>Random House</publisher>
        <year>1960</year>
        <price>$8.99</price>
    </book>
    <book>
        <title>Where the Wild Things Are</title>
        <author>Maurice Sendak</author>
        <publisher>Harper &amp; Row</publisher>
        <year>1963</year>
        <price>$12.99</price>
    </book>
</bookstore>
